name: Update-Readme-File
description: 'updating README.md with a readme from another repo'
author: Boris Dundakov

inputs:

  myToken:
    description: The PAT access token
    required: False

outputs:
  key:
    description: the key for the PAT

# node.js setup
runs:
  using: 'node16'
  main: 'dist/index.js'