name: Update-Readme-File

on:
  push:
    branches:
     - 'main'

jobs:
  update-Readme-File-job:
   runs-on: ubuntu-latest
   name: update-Readme-File

   steps:
     - name: Set Node.js 16.x
       uses: actions/setup-node@v3.5.1
       with:
         node-version: 16.x

     - name: Install dependencies
       run: npm install

     - name: Building action
       run: npm run build

     - name: Checkout current repository
       uses: actions/checkout@v3


     - name: copy action step
       id: copy
       uses: ./
       with:
         myToken: ${{ secrets.GITHUB_TOKEN}}
    #  - name: Display JS output
    #    id: content
    #    with:
    #     node-version: 16.x

    #    uses: 'RepoToCopyInto/index.js'